# Generated by Django 5.0.11 on 2025-04-28 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailattachment',
            name='size',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
