# Generated by Django 5.0.11 on 2025-02-19 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertymanagerprofile',
            name='middle_name',
        ),
    ]
