# Generated by Django 5.1.3 on 2025-01-29 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_propertymanagerprofile_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantprofile',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
    ]
