# Generated by Django 5.0.11 on 2025-02-19 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_propertymanagerprofile_middle_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertymanagerprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='propertymanagerprofile',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='tenantprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='tenantprofile',
            name='last_name',
        ),
    ]
