# Generated by Django 5.1.3 on 2025-01-30 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_tenantprofile_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertymanagerprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='tenantprofile',
            name='email',
        ),
    ]
