# Generated by Django 5.1.3 on 2025-02-01 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accomodations', '0012_merge_20250129_2345'),
        ('users', '0004_remove_propertymanagerprofile_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantprofile',
            name='rented_property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenants', to='accomodations.property'),
        ),
    ]
