# Generated by Django 5.1.3 on 2025-02-01 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accomodations', '0013_house'),
        ('users', '0005_tenantprofile_rented_property'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenantprofile',
            name='middle_name',
        ),
        migrations.RemoveField(
            model_name='tenantprofile',
            name='rented_property',
        ),
        migrations.AddField(
            model_name='tenantprofile',
            name='rented_house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenants', to='accomodations.house'),
        ),
        migrations.AddField(
            model_name='tenantprofile',
            name='rented_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenants', to='accomodations.room'),
        ),
    ]
