# Generated by Django 5.1.3 on 2025-02-04 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accomodations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='no_of_room',
        ),
    ]
