# Generated by Django 5.1.3 on 2024-12-03 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accomodations', '0002_amenity_remove_property_amenities_property_amenities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amenity',
            name='icon',
        ),
    ]
