# Generated by Django 5.0.11 on 2025-02-06 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accomodations', '0003_remove_house_is_available_remove_room_is_available_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
