# Generated by Django 5.1.3 on 2024-12-04 10:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accomodations', '0004_remove_property_image_remove_room_images_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='managers',
            field=models.ManyToManyField(blank=True, related_name='managed_properties_list', to=settings.AUTH_USER_MODEL),
        ),
    ]
