# Generated by Django 5.0.11 on 2025-02-18 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accomodations', '0005_room_is_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='facilities',
        ),
        migrations.RemoveField(
            model_name='room',
            name='facilities',
        ),
        migrations.DeleteModel(
            name='Facility',
        ),
    ]
