# Generated by Django 5.1.3 on 2024-12-17 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accomodations', '0005_property_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyimage',
            name='image',
            field=models.ImageField(upload_to='img/property_images/'),
        ),
    ]
