# Generated by Django 5.1.3 on 2024-12-17 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accomodations', '0006_alter_propertyimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyimage',
            name='image',
            field=models.ImageField(upload_to='property_images/'),
        ),
    ]
