# Generated by Django 5.1.3 on 2024-12-23 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accomodations', '0007_alter_room_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='facilities',
            field=models.ManyToManyField(blank=True, related_name='rooms', to='accomodations.facility'),
        ),
    ]
