# Generated by Django 5.0.11 on 2025-02-19 14:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accomodations', '0007_booking_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='facebook_url',
            field=models.URLField(blank=True, max_length=500, null=True, validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AddField(
            model_name='house',
            name='instagram_url',
            field=models.URLField(blank=True, max_length=500, null=True, validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AddField(
            model_name='room',
            name='facebook_url',
            field=models.URLField(blank=True, max_length=500, null=True, validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AddField(
            model_name='room',
            name='instagram_url',
            field=models.URLField(blank=True, max_length=500, null=True, validators=[django.core.validators.URLValidator()]),
        ),
    ]
