# Generated by Django 5.1.3 on 2024-12-17 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accomodations', '0007_alter_propertyimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='total_rooms',
            field=models.IntegerField(default=1),
        ),
    ]
