# Generated by Django 5.0.11 on 2025-03-08 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accomodations', '0008_house_facebook_url_house_instagram_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
