# Generated by Django 5.0.11 on 2025-03-08 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accomodations', '0009_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='city',
        ),
    ]
