# Generated by Django 5.1.3 on 2024-12-18 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accomodations', '0010_alter_room_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
