# Generated by Django 5.1.3 on 2025-01-29 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accomodations', '0008_facility_room_facilities'),
        ('accomodations', '0011_property_slug'),
    ]

    operations = [
    ]
