# Generated by Django 5.0.11 on 2025-03-11 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accomodations', '0011_property_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='description',
        ),
    ]
