# Generated by Django 5.1.3 on 2025-02-01 13:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accomodations', '0013_house'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='property',
            name='price_per_night',
        ),
        migrations.RemoveField(
            model_name='property',
            name='total_rooms',
        ),
        migrations.AddField(
            model_name='room',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='managers',
            field=models.ManyToManyField(blank=True, related_name='managed_properties', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='property',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='type_of_bed',
            field=models.CharField(choices=[('single', 'Single'), ('double', 'Double'), ('queen', 'Queen'), ('king', 'King')], default='single', max_length=50),
        ),
        migrations.CreateModel(
            name='HouseImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='house_images/')),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='accomodations.house')),
            ],
        ),
        migrations.DeleteModel(
            name='PropertyImage',
        ),
    ]
