# Generated by Django 5.0.11 on 2025-03-12 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accomodations', '0013_rule_alter_house_description_alter_room_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='rules',
        ),
        migrations.AddField(
            model_name='property',
            name='rules',
            field=models.ManyToManyField(blank=True, related_name='properties', to='accomodations.rule'),
        ),
    ]
