# Generated by Django 5.1.3 on 2025-02-01 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accomodations', '0014_remove_property_is_available_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='number_of_rooms',
            field=models.IntegerField(default=1),
        ),
    ]
