# Generated by Django 5.1.3 on 2025-02-04 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accomodations', '0016_property_latitude_property_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='no_of_bathroom',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='house',
            name='no_of_room',
            field=models.IntegerField(default=1),
        ),
    ]
