# Generated by Django 5.1.3 on 2025-02-04 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accomodations', '0017_house_no_of_bathroom_house_no_of_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='facilities',
            field=models.ManyToManyField(blank=True, related_name='houses', to='accomodations.facility'),
        ),
    ]
