# Generated by Django 5.0.11 on 2025-02-06 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='payment_method_qr_codes/'),
        ),
    ]
