# Generated by Django 5.0.11 on 2025-02-18 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0002_alter_paymentmethod_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='payment_method_qr_codes'),
        ),
    ]
