# Generated by Django 5.1.3 on 2025-02-01 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0003_paymentmethod_alter_payment_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='name',
            field=models.CharField(choices=[('bank_account', 'Bank Account'), ('zelle', 'Zelle'), ('venmo', 'Venmo'), ('paypal', 'PayPal')], max_length=50, unique=True),
        ),
    ]
